---
# tasks file for ansible-LibvirtSetup

- name: execute if RedHat
  import_tasks: redhat.yaml
  when: ansible_os_family == "RedHat"

- name: execute if Debian
  import_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- import_tasks: pxe_setup.yaml
- import_tasks: firewall.yaml
